CLAVE_RCPN = "RCPN210217"
CLAVE_RESERVAS = "reservas.2022++"

[supabase]
url = "https://jtkxcptryjhpkkuokrbj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0a3hjcHRyeWpocGtrdW9rcmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNDk2MDUsImV4cCI6MjEwNDkyNTYwNX0.dpyqtqR38UDC6X-HYUW4iFRTeB4ZCo-XxtOsu_DDk8w"

