CLAVE_RCPN = "RCPN210217"

[supabase]
url = "https://jtkxcptryjhpkkuokrbj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0a3hjcHRyejhpbnBna3Vva3JiaiIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg5MzQ5NjA1LCJleHBzIjoyMTA0OTI1NjA1fQ.dpyqtqR38UDC6X-HYUW4iFRTeB4ZCo-XxtOsu_DDk8w"